# Generated by Django 3.1.2 on 2020-11-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitcoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=11, max_digits=17, verbose_name='Цена')),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
